language: c

os:
  - osx

install:
  - curl -R -O http://www.lua.org/ftp/lua-5.4.1.tar.gz
  - tar zxf lua-5.4.1.tar.gz
  - cd lua-5.4.1
  - make macosx test
  - cd ..

script:
  - cd tests
  - ../lua-5.4.1/src/lua tests.lua
