language: c

os:
  - linux

install:
  - curl -R -O http://www.lua.org/ftp/lua-5.4.3.tar.gz
  - tar zxf lua-5.4.3.tar.gz
  - cd lua-5.4.3
  - make linux test
  - cd ..

script:
  - cd src
  - ../lua-5.4.3/src/lua eg.lua
