#!/usr/bin/env bash


############# assert dirs exist
mkdir -p $Ell/etc
mkdir -p $Ell/src
mkdir -p $Ell/docs
f=$Ell/docs/.nojekyll; [[ -f "$f" ]] || touch $f 

docs() {
  head=`gawk -f $Ell/etc/para2.awk $Ell/README.md`
  cd $Ell/src; 
  for i in *.lua; do
    gawk -v txt="$head"  -f $Ell/etc/addheader.awk $i > ../docs/$i
  done
  cd ../docs
  pycco  -d $Ell/docs *.lua
  cp $Ell/etc/pycco.css $Ell/docs
  rm $Ell/docs/*.lua
} 

alias gp="git add *;git commit -am save;git push;git status"
alias ls="ls -G"
alias tmux="$(which tmux) -f $Ell/etc/tmux-conf "
alias lldoc="lua ldoc.lua -f markdown -a -p KEYS -t keys -S -o rast rast.lua "
alias vi="vim -u $Ell/etc/vimrc "
alias vims="vim +PluginInstall +qall"         
alias lldoc="ldoc  -d ../docs -o rast -f markdown -p KEYS -t rast rast.lua"


here() { cd $1; basename `pwd`; }

PROMPT_COMMAND='echo -ne "🌙 $(git branch 2>/dev/null | grep '^*' | colrm 1 2):";PS1="$(here ..)/$(here .):\!\e[m ▶ "'
