#!/usr/bin/env bash


############# assert dirs exist
mkdir -p $Ell/etc
mkdir -p $Ell/src
mkdir -p $Ell/docs
f=$Ell/docs/.nojekyll; [[ -f "$f" ]] || touch $f 

docs() {
  (cd $Ell/src;  pycco  -d $Ell/docs *.lua)
  cp $Ell/etc/pycco.css $Ell/docs
} 

alias gp="git add *;git commit -am save;git push;git status"
alias ls="ls -G"
alias tmux="$(which tmux) -f $Ell/etc/tmux-conf "
alias vi="vim -u $Ell/etc/vimrc "
alias vims="vim +PluginInstall +qall"         

here() { cd $1; basename `pwd`; }

PROMPT_COMMAND='echo -ne "🌙 $(git branch 2>/dev/null | grep '^*' | colrm 1 2):";PS1="$(here ..)/$(here .):\!\e[m ▶ "'
