#!/usr/bin/env bash

noPara1()  { gawk '
  BEGIN {RS=""; FS="\n"}
  NR==1 { next }
        { print($0 "\n")  }' 
}

classify() { gawk '
  /^--\[\[/,/--\]\]/ { print "DOC " $0; next }
  /^-- /             { print "DOC " $0; next;}
                     { print "CODE "$0}' 
}

apply() { gawk '
  BEGIN {top=1}
      { now=$1
        gsub(/(DOC |CODE )/,"");
        apply(now,b4,last) 
        last=$0
        b4=now} 
END   { apply(now,b4,last)
        if (now=="CODE") print "```" }

function apply(now,b4,last) {
  gsub(/^(-- |--\[\[[ \t]*|--\]\])/,"",last)
  if  (now==b4)  
     print(last)
  else {
   if (last !~ /^[ \t]*$/) last=last "\n"
   if (now=="CODE") {
     printf(last); 
    print "\n\n<details><summary>code</summary>\n\n"
     print"\n```lua\n"}
   if (now=="DOC")  {printf(last)
                    if (!top)   print"```\n\n</details>\n\n" }
                    top=0}}' 
}


f=${1%.*}
shift
title="$@"
(cat<<EOF
---
title: "File $title"
---

EOF
cat $f | noPara1 | classify  | apply) > ../docs/$f.md
# cd ../docs
# pandoc -f markdown  --template=ez.html --toc  --mathjax \
#        --lua-filter linenums.lua \
#        --highlight-style pygments --css style.css -s $f.md -o $f.html
# git add $f.html
# open $f.html

