#!/usr/bin/env bash

noPara1()  { gawk '
  BEGIN {RS=""; FS="\n"}
  NR==1 { next }
        { print($0 "\n")  }' 
}

classify() { gawk '
  /^--\[\[/,/--\]\]/ { print "DOC " $0; next }
  /^-- /             { print "DOC " $0; next;}
                     { print "CODE "$0}' 
}

apply() { gawk '
  BEGIN {top=1}
      { now=$1
        gsub(/(DOC |CODE )/,"");
        apply(now,b4,last) 
        last=$0
        b4=now} 
END   { apply(now,b4,last)
        if (now=="CODE") print "```" }

function apply(now,b4,last) {
  gsub(/^(-- |--\[\[[ \t]*|--\]\])/,"",last)
  if  (now==b4)  
     print(last)
  else {
    if (last !~ /^[ \t]*$/) last=last "\n"
    if (now=="CODE") {
      printf(last); 
      #print "\n\n<ul><details><summary>code</summary>\n\n"
      print"\n```lua\n"  }
    if (now=="DOC")  {
      printf(last)
      if (!top)  print"```"
      #if (!top)  print</details></ul>\n\n" 
    }
    top=0}}' 
}


f=${1%.*}
shift
title="$@"
(cat<<EOF

#  $title

EOF
cat <<'EOF'

<img alt="Lua" src="https://img.shields.io/badge/lua-v5.4-blue">
<a href="https://github.com/timm/keys/blob/master/LICENSE.md"><img 
alt="License" src="https://img.shields.io/badge/license-unlicense-red"></a> <img 
src="https://img.shields.io/badge/purpose-ai%20,%20se-blueviolet"> <img 
alt="Platform" src="https://img.shields.io/badge/platform-osx%20,%20linux-lightgrey"> <a 
href="https://github.com/timm/keys/actions"><img 
src="https://github.com/timm/keys/actions/workflows/unit-test.yml/badge.svg"></a> 

<hr>
classes: 
(data <a href="rows.md">rows</a>, <a href="row.md">row</a>);
(cols <a href="num,md">num</a> <a href="sym.md">sym</a> <a href="skip,md">skip</a>)<br>
(functions: <a href="strings.md">strings</a>, <a href="maths.md">maths</a>)
<hr>

EOF


cat $f | noPara1 | classify  | apply) > ../docs/$f.md
# cd ../docs
# pandoc -f markdown  --template=ez.html --toc  --mathjax \
#        --lua-filter linenums.lua \
#        --highlight-style pygments --css style.css -s $f.md -o $f.html
# git add $f.html
# open $f.html

