#!/usr/bin/env bash

# misc convenient shortcuts

Src=$(cd $( dirname "${BASH_SOURCE[0]}" ) && pwd )/..
chmod +x $Src/etc/sh

alias ls="ls -G"
alias gp="git add *; git commit -am saving; git push; git status"
alias axe="lua axe.lua"
alias oks="(date; cd $Src/tests;                         lua tests.lua)"
alias okspy="(rerun '$Src/etc/sh -t')"

docs() {
  mkdir -p $Src/docs
  (cd $Src/src; pycco -d $Src/docs *.lua)
  (cd $Src; markdown README.md > $Src/docs/index.html)
  cp $Src/etc/pycco.css $Src/docs
}


if [ "$1" == "-t" ]; then
  a[0]="tux" #
  a[1]="bud-frogs"  #
  a[2]="eyes"
  a[3]="flaming-sheep"
  a[4]="hellokitty"
  a[5]="meow"
  a[6]="small"
  r=$[ $RANDOM % 7 ]
  f=${a[$r]}
  cd $Src/tests
  date +"%r" | cowsay -f $f
  lua tests.lua
fi

