remote_theme: diezcami/arctic-fox-theme

title: Keys
email: 
description: > # this means to ignore newlines until "baseurl:"
  Stuff and things
baseurl: "/keys" # the subpath of your site, e.g. /blog/
url: "http://menzies.us" # the base hostname & protocol for your site
twitter_username: timmenzies
github_username: timm

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]

